sources:
  - id: drr-repo
    project_id: drr
    root_path: /Users/christopher.peck/DRR
    include_glob: "**/*"
    exclude_glob: "**/.git/**"

  # Additional sources can be added here:
  # - id: privacy-pay
  #   project_id: privacypay
  #   root_path: /Users/christopher.peck/PrivacyPay
  #   include_glob: "**/*"
  #   exclude_glob: "**/.git/**"
  #
  # - id: flywheel
  #   project_id: flywheel
  #   root_path: /Users/christopher.peck/Flywheel
  #   include_glob: "**/*"
  #   exclude_glob: "**/.git/**"

