sources:
  - id: drr-repo
    project_id: drr
    root_path: /Users/christopher.peck/DRR
    include_glob: "**/*"
    exclude_glob: "**/.git/**"

  # ChatDO itself can be added later:
  # - id: chatdo-repo
  #   project_id: chatdo
  #   root_path: /Users/christopher.peck/ChatDO
  #   include_glob: "**/*"
  #   exclude_glob: "**/.git/**"

